---
services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_SCHEDULER_EMBED_URL: ${NEXT_PUBLIC_SCHEDULER_EMBED_URL}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
    ports:
      - "3020:3000"
    env_file:
      - .env
    networks:
      - shared_webnet

networks:
  shared_webnet:
    external: true
